### ISSUE TITLE
dependency on @angular-mdc/web

### ISSUE THREAD

**Issue by CramericaIndustries** [kctang/dialog-service#1]
Sorry if this is a newbie question. In my project I'm using Angular Material (`MatDialogServiceModule`) and not Angular-MDC.
However to make the dialog-service work I had to install the '@angular-mdc/web' package.

This is the error message I got when running 'ng serve':
```
ERROR in node_modules/dialog-service/lib/MdcDialogService.d.ts(1,27): error TS2307: Cannot find module '@angular-mdc/web'.
node_modules/dialog-service/lib/mdc/Form.component.d.ts(2,30): error TS2307: Cannot find module '@angular-mdc/web'.
```
The error disappeared after I installed the '@angular-mdc/web' package.
I wanted to avoid installing packages that I'm actually not using in my project.

**Comment by kctang** [comment]
I believe that is my mistake when publishing the package. I need to do some clean up to make sure the dependencies for respective UI library does not get in each other's way.

Thanks for reporting this issue. I will fix it ASAP.

**Comment by kctang** [comment]
Hi @CramericaIndustries, I just published v0.0.3.

It should make UI libraries optional - so it is developer's responsibility to add appropriate library.

You can take a look at a demo app specifically for Angular Material [here](https://github.com/kctang/dialog-service-mat-demo).

Hope this helps and thanks for trying this library!

**Comment by kctang** [comment]
Closing this issue. @CramericaIndustries, if you can't get it to work, re-open and @ me.

Also, if you like what it does, do give it a star as motivation for me to work on this library. :-)

**Comment by CramericaIndustries** [comment]
@kctang I can confirm that it's working now without the '@angular-mdc/web' being present.
Thank you very much! I had a look at several dialog libs and your dialog-service module was the best. 👍
And I gave you your :star:
